#!/bin/sh

if [ -z "$(command -v x11docker)" ]; then
  echo "'x11docker' is not available."
  echo "Please install it from: https://github.com/mviereck/x11docker/releases"
  exit 1
fi

. ./setversion
# example starter to run the image using podman in a wayland session
x11docker --backend=podman --hostwayland -q --env HOME=/root --workdir=/root/models -i -- --rm -v "$(pwd):/root/models" -- ghcr.io/omnetpp/omnetpp-gui:u24.04-$VERSION -c /bin/bash
